#  Feature Engineering
## Feature Elimination - Dropping the unwanted feature
## Feature Addition-Adding some new features
## Featuier Slection

In [3]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix 

In [ ]:
# feature selection is used to optimize the model with reduce and select the  optimum number 
of featutes to get maximum number of accuracy 

In [11]:
data=load_breast_cancer()

In [5]:
df


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
df=pd.DataFrame(data=df.data,columns=df['feature_names'])

In [9]:
x=df

In [13]:
x

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [14]:
y=data.target

In [15]:
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [16]:
x.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry      

In [17]:
x.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [24]:
xtr,xts,ytr,yts=train_test_split(x,y,train_size=0.80)

# select fom model



In [19]:
from sklearn.feature_selection import SelectFromModel

#### model1

In [21]:
stmf=SelectFromModel(estimator=RandomForestClassifier(n_estimators=50,criterion='gini',max_depth=10))

In [22]:
stmf

SelectFromModel(estimator=RandomForestClassifier(max_depth=10, n_estimators=50))

In [25]:
stmf.fit(xtr,ytr)

SelectFromModel(estimator=RandomForestClassifier(max_depth=10, n_estimators=50))

#### Transform

In [27]:
stmf.get_support()

array([ True, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True,  True, False, False,  True,
        True, False, False])

In [30]:
x.columns[stmf.get_support()]

Index(['mean radius', 'mean concavity', 'mean concave points', 'area error',
       'worst radius', 'worst perimeter', 'worst area', 'worst concavity',
       'worst concave points'],
      dtype='object')

#### x-Train

In [31]:
xtr_transformed=stmf.transform(xtr)

In [33]:
xtr_transformed.shape

(455, 9)

#### x-Test

In [34]:
xts_transformed=stmf.transform(xts)

In [35]:
xts_transformed.shape

(114, 9)

#### Creating common function

In [47]:
def runRandomforest(xtr,xts,ytr,yts):
    rfmodel=RandomForestClassifier(max_depth=7)
    rfmodel.fit(xtr,ytr)
    ytrp=rfmodel.predict(xts)
    print("acc:", accuracy_score(yts,ytrp))
    print("cmx:",confusion_matrix(yts,ytrp))

#### Checking

In [51]:
%%time
runRandomforest(xtr,xts,ytr,yts)

acc: 0.9736842105263158
cmx: [[37  3]
 [ 0 74]]
CPU times: total: 109 ms
Wall time: 238 ms


In [52]:
%%time
runRandomforest(xtr_transformed,xts_transformed,ytr,yts)

acc: 0.9385964912280702
cmx: [[35  5]
 [ 2 72]]
CPU times: total: 109 ms
Wall time: 198 ms


# Recursive Feature elimination

In [55]:
from sklearn.feature_selection import  RFE

#### Model2

In [56]:
rfemodel=RFE(estimator=RandomForestClassifier(n_estimators=50,criterion='gini',max_depth=10))

In [57]:
rfemodel.fit(xtr,ytr)

RFE(estimator=RandomForestClassifier(max_depth=10, n_estimators=50))

#### Transform


In [58]:
rfemodel.get_support()

array([ True,  True,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False])

In [59]:
x.columns[rfemodel.get_support()]

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean concavity', 'mean concave points', 'area error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area', 'worst smoothness',
       'worst concavity', 'worst concave points', 'worst symmetry'],
      dtype='object')

In [66]:
xtr_transformedrfe=rfemodel.transform(xtr)
xts_transformedrfe=rfemodel.transform(xts)

In [67]:
xtr_transformedrfe.shape

(455, 15)

In [68]:
xts_transformedrfe.shape

(114, 15)

In [70]:
%%time
runRandomforest(xtr_transformedrfe,xts_transformedrfe,ytr,yts)

acc: 0.9736842105263158
cmx: [[37  3]
 [ 0 74]]
CPU times: total: 109 ms
Wall time: 277 ms


In [73]:
import numpy as np

#### Creating loop for check optimum Columns

In [72]:
for i in range(1,len(x.columns)):
    rfemodel=RFE(estimator=RandomForestClassifier(n_estimators=50,criterion='gini',max_depth=10),n_features_to_select=i)
    rfemodel.fit(xtr,ytr)
    xtr_transformedrfe=rfemodel.transform(xtr)
    xts_transformedrfe=rfemodel.transform(xts)

    print(xtr_transformedrfe.shape)
    print("num of features",i)
    runRandomforest(xtr_transformedrfe,xts_transformedrfe,ytr,yts)
    print("#########")
    

(455, 1)
num of features 1
acc: 0.8947368421052632
cmx: [[32  8]
 [ 4 70]]
#########
(455, 2)
num of features 2
acc: 0.868421052631579
cmx: [[30 10]
 [ 5 69]]
#########
(455, 3)
num of features 3
acc: 0.8771929824561403
cmx: [[30 10]
 [ 4 70]]
#########
(455, 4)
num of features 4
acc: 0.9385964912280702
cmx: [[35  5]
 [ 2 72]]
#########
(455, 5)
num of features 5
acc: 0.9298245614035088
cmx: [[34  6]
 [ 2 72]]
#########
(455, 6)
num of features 6
acc: 0.9473684210526315
cmx: [[36  4]
 [ 2 72]]
#########
(455, 7)
num of features 7
acc: 0.9298245614035088
cmx: [[34  6]
 [ 2 72]]
#########
(455, 8)
num of features 8
acc: 0.9736842105263158
cmx: [[37  3]
 [ 0 74]]
#########
(455, 9)
num of features 9
acc: 0.9649122807017544
cmx: [[37  3]
 [ 1 73]]
#########
(455, 10)
num of features 10
acc: 0.956140350877193
cmx: [[37  3]
 [ 2 72]]
#########
(455, 11)
num of features 11
acc: 0.9649122807017544
cmx: [[37  3]
 [ 1 73]]
#########
(455, 12)
num of features 12
acc: 0.9736842105263158
cmx: [[37 